sonar.projectKey=mesachef
sonar.projectName=mesachef
sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,build/**,.next/**,coverage/**,.github/**,public/**,**/*.test.*,**/*.spec.*
